export const metadata = {
    title: 'Profile | Next',
    description: 'Generated by create next app',
  }


const ProfilePage = () => {
    return (
        <div>
            Profile page
        </div>
    );
};

export default ProfilePage;