export const metadata = {
    title: 'Add-Manage | Next',
    description: 'Generated by create next app',
  }

const AddManage = () => {
    return (
        <div>
            AddManage
        </div>
    );
};

export default AddManage;