// "use client";

import Link from "next/link";
// import { useRouter } from "next/navigation";

export const metadata = {
    title: 'BlogPage | Next',
    description: 'Generated by create next app',
}

const blogs = [
    {
        id: 1,
        year: 2016,
        title: "title 1"
    },
    {
        id: 2,
        year: 2018,
        title: "title 2"
    },
    {
        id: 3,
        year: 2020,
        title: "title 3"
    },

]


const BlogPage = () => {
    // const router = useRouter();
    return (
        <div className="container mx-auto">
            {
                blogs.map(({ id, year, title }) => (
                    <Link className='block p-2 my-2 border border-blue-500'
                        href={{
                            pathname: `/blogs/${year}/${id}`,
                            query:{
                                title:title,
                            },
                        }} 
                        // onClick={()=> router.push(`/blogs/${year}/${id}?title=${title}`)}
                        key={id}>
                        {title}
                    </Link>
                ))
            }
        </div>
    );
};

export default BlogPage;