export const metadata = {
    title: 'About | Next',
    description: 'Generated by create next app',
  }

const About = () => {
    return (
        <div>
            <h2>About Page</h2>
        </div>
    );
};

export default About;