export const metadata = {
    title: 'Add-Product | Next',
    description: 'Generated by create next app',
  }


const AddProduct = () => {
    return (
        <div>
            Addproduct
        </div>
    );
};

export default AddProduct;